Repository LouisBarranqueiro/hexo-theme-tranquilpeak, pull requests merged in 2019-06, with the labels that each got.

#540 Update the Algolia library icon
  layout/_partial/search.ejs
  source/_images/logo-algolia-nebula-blue-full.svg
Labels: status: in progress, type: bug

#533 Implement Gitalk as a comment provider
  _config.yml
  languages/en.yml
  layout/_partial/post.ejs
  layout/_partial/post/actions.ejs
  layout/_partial/post/gitalk.ejs
  layout/_partial/script.ejs
Labels: status: in progress, type: enhancement

#557 Update README to include gitalk as a comment provider
  README.md
Labels: type: enhancement

#547 Clicking outside of about card dismisses card
  source/_css/layouts/_about.scss
  source/_js/about.js
Labels: status: in progress, type: enhancement

#527 Video Tag
  DOCUMENTATION.md
  scripts/tags/video.js
  source/_css/components/_figure.scss
Labels: status: in progress, type: feature
